### ISSUE TITLE
Is this project related to alation data catalog product for containerizing it 

### ISSUE THREAD

**Issue by AllamSudhakara** [chris-henderson-alation/alation_docker#1]
Hi,

I am little confused on this project purpose. I am assuming that you created this solution for properly building alation data catalog image for many a platforms and for making sure that patches/enhancements could be pushed appropriately. Could you please confirm? Where are the rpm and deb files located?

Regards,
Sudhakar

**Comment by chris-henderson-alation** [comment]
@AllamSudhakara this is not a repo in the Alation org. This is a repo tied to my user account that I used at one point to test out ideas.
